- name: Playbook for fetching files
  hosts: "{{ target }}"
  gather_facts: no

  become: true
  become_user: root

  vars_prompt:
    - name: "target"
      prompt: "Input target host"
      default: all
      private: no

    - name: "inputfile"
      prompt: "Input your file list"
      private: no

    - name: "savedir"
      prompt: "Input a save directory"
      default: fetched
      private: no

  vars:
    facts_dir: "{{ savedir }}/facts"

  pre_tasks:
    - name: Get ansible_facts 
      local_action: raw ansible -i hosts "{{ target }}" -m setup --tree "{{ facts_dir }}"
      become: false
    - name: Pre setup (create lists for fetch)
      local_action: raw ./tools/create_var.pl "{{ inputfile }}"
      become: false

  roles:
    - fetch_file
    #- { role: hoge, when: "ansible_distribution == 'hoge'" }

  post_tasks:
    - name: Convert JSON to csv 
      local_action: raw ./tools/conv.pl "{{ facts_dir }}"
      run_once: true
      become: false
