- name: Playbook for fetching files
  hosts: "{{ target }}"
  gather_facts: no

  become: true
  become_user: root

  vars_prompt:
    - { name: "target" , prompt: "Input target host" ,  default: all , private: no }
    - { name: "inputfile" , prompt: "Input your file list" , default: sample_filelist.txt , private: no }
    - { name: "inputcommand" , prompt: "Input your command list" , default: sample_comlist.txt , private: no }
    - { name: "remtemp" , prompt: "Input remote temp directory " , default: /tmp/remtemp , private: no }
    - { name: "savedir" , prompt: "Input a save directory" , default: fetched , private: no }

  pre_tasks:
    - block:
        - name: Pre get ansible_facts 
          local_action: raw ansible -i hosts "{{ target }}" -m setup --tree "{{ facts_dir }}"
        - name: Pre setup (create lists for fetch)
          local_action: raw ./tools/create_var1.pl "{{ inputfile }}"
      become: false

    - block:
        - name: Pre get command list
          local_action: raw ./tools/create_var2.pl "{{ inputcommand }}"
      when: comget == "y"

  roles:
    - fetch_file
    - { role: run_out_fetch, when: "comget == 'y'" }

  post_tasks:
    - name: Convert JSON to csv 
      local_action: raw ./tools/conv.py "{{ facts_dir }}"
      run_once: true
      become: false
      when: json2csv == "y"
